@startuml
left to right direction
actor Anonimo as a
actor User_Cadastrado as u

package Aplicação{
  usecase "Compartilhar evento" as UC1
  usecase "Se cadastrar " as UC2
  usecase "Visualizar calendário acadêmico e eventos gerais" as UC3
  usecase "Fazer login" as UC4
  usecase "Editar informações pessoais" as UC5
  usecase "Receber notificações" as UC6
  usecase "Filtrar evento por categoria" as UC7
  usecase "Receber notificações" as UC8
  usecase "Gerenciar Eventos" as UC9
  usecase "Visualizar eventos de curso" as UC10
}

package Servidor{
  usecase "Validar Campus" as UC11
  usecase "Fornecer Informações" as UC12
  usecase "Enviar Notificações para o  Usuário" as UC13
  usecase "Realizar Login do Usuário" as UC14
  usecase "Salvar Dados" as UC15
}

a <|-- u
a --> UC1
a --> UC2
a --> UC3

u --> UC4
u --> UC10
u --> UC9
u --> UC8
u --> UC7
u --> UC5

UC3 --> UC12
UC7 --> UC9
UC2 .> UC11 :include
UC4 .> UC11 :include
UC5 .> UC11 :include
UC14 .> UC11 :extend
UC15 .> UC11 :extend

@enduml
