@startuml
skinparam BackgroundColor transparent
skinparam componentStyle uml2

component Client {
      component "Calendário" {
   }
      component "LoginCadastro" {
   }
      component "InterfaceGráfica"{
   }
      component "RegistrodeEvento"{
   }
}

component API {
  component "ControladorUsuario" {
  }
  component "ControladorEvento" {
  }
  component "ControladorNotificação" {
  }
  component "BancoDeDados" {
  }
}

Client -- () .
. -- API :API>>Cliente
API -- () ..
.. -- Client :Cliente>>API

Calendário ..> InterfaceGráfica
LoginCadastro ..> InterfaceGráfica
RegistrodeEvento ..> InterfaceGráfica

ControladorUsuario --> BancoDeDados
ControladorEvento --> BancoDeDados
ControladorNotificação --> BancoDeDados



@enduml
