@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml

Person(user, "Usuário", "Usuarios do sistema que desejam acesso ao calendario acadêmico")
System(app, "Sistema UnicalUPE","Permite que os usuários visualizem o calendário acadêmico, podendo receber notificações, visualizar, adicionar e gerenciar informações do calendário")
System_Ext(auth, "Google Authenticator", "O usuário valida seu identidade através da aplicação")
System_Ext(server, "Heroku", "Responsável por hospedar o banco de dados")

Rel(user, app, "Buscam, modificam e adicionam eventos acadêmicos usando o")
Rel(app, auth, "Utiliza o serviço de autenticação do")
Rel(app, server, "Está hospedado no")
@enduml
