@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml

Person(pbc, "Usuário", "Usuarios do sistema que acessam os calendários")
System(ibs, "Sistema UnicalUPE", "Permite que os usuários visualizem o calendário acadêmico. Podem receber notificações e adicionar/gerenciar informações ao calendário")
System(es, "Google Authenticator", "realizado através da autenticação com o login do google")
System(mbs, "Servidor UnicalUPE", "Responsável por salvar os dados, fornecer informações, enviar notificaçõesa ao usuário, validar campos")

Rel(pbc, ibs, "Usuários")
Rel(es, pbc, "Envia e-mails de atutenticação")
Rel(ibs, es, "Solicita Login")
Rel(ibs, mbs, "Usuários")
@enduml
