@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/users.puml

!include DEVICONS/msql_server.puml
!include FONTAWESOME/server.puml
!include FONTAWESOME/envelope.puml

' LAYOUT_WITH_LEGEND()

Person(users, "Usuário", "Usuarios do sistema que desejam acesso ao calendario acadêmico",  $sprite="users")

System_Boundary(App, "UnicalUPE") {

    Component(appUnical, "UnicalUPE App", "App Mobile: React Native", "Dentro da aplicação o usuário tem acesso a ações como visitar o calendário, visualizar eventos, acesso a lista de eventos, notificaçoes dos eventos. Disponível para sistemas Andorid.")

    System_Boundary(Heroku,"Heroku") {
        ContainerDb(bdados, "UnicalUPE BD", "Banco de Dados: PostgreSQL", "Central de armazenamento de dados da aplicação, dados dos eventos, notificações, usuarios", "msql_server")
        Component(systemapi, "UnicalUPE API", "API: Java(Spring Boot)", "API que será consumida pelo App Mobile", "server")
    }
}

System_Ext(goauth, "Google Authenticator", "O usuário valida seu identidade através da aplicação.")

Rel(appUnical, goauth,"Utiliza a biblioteca de frontend do")
Rel(appUnical, goauth,"Utiliza a biblioteca de backend do")
Rel(appUnical, systemapi, "Se comunica com")


Rel(users, appUnical, "Visualizaçao da aplicação baseada na foram de login");
Rel(systemapi, bdados, "Utiliza o SGBD");

@enduml
