@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/users.puml
!include FONTAWESOME/server.puml
!include DEVICONS/msql_server.puml

Component(appUnical, "UnicalUPE App", "App Mobile: React Native", "O acesso do sistema para os usuários se da a partir do app mobile para sistemas Andoid.")
Container_Boundary(spa, "UnicalUPE (API)"){
    Component(ctrlEventos, "Controlador de Eventos", "Typescript" ,"Responsável por controlar os eventos usando CRUDS")
    Component(ctrlNotificacoes, "Controlador de Notificações", "Typescript" ,"Responsável por controlar as notificações para o usuário")
    Component(ctrlUsuario, "Controller de usuários", "Typescript" ,"Responsável por controlar os dados do usuário")
    Component(ctrlLogin, "Controller de Login", "Typescript", "função responsável por autenticar e validar login no sistema")

    Component(servLogin, "Service do Login", "Typescript", "função responsável por carregar a página após validação dos dados do usuário")
    Component(servEvent, "Service de Eventos", "Typescript" ,"Responsável pela comunicação com os dados dos eventos")
    Component(servNotifications, "Service de Notificação", "Typescript" ,"Responsável pela comunicação com os dados das notificações")
    Component(servUser, "Service de Usuário", "Typescript" ,"Responsável pelos dados dos usuários")
}

System_Ext(goauth, "Google Authenticator", "O usuário valida sua identidade através da aplicação.")
ContainerDb(bdados, "Banco de Dados: PostgreSQL", "Central de armazenamento de dados da aplicação, dados dos eventos, notificações, usuarios", "msql_server")

Rel(appUnical, ctrlEventos, "Faz chamadas da API para", "JSON/HTTPS");
Rel(appUnical, ctrlNotificacoes, "Faz chamadas da API para", "JSON/HTTPS");
Rel(appUnical, ctrlUsuario, "Faz chamadas da API para", "JSON/HTTPS");
Rel(appUnical, ctrlLogin, "Faz chamadas da API para", "JSON/HTTPS");

Rel(ctrlEventos, servEvent, "usa");
Rel(ctrlNotificacoes, servNotifications, "usa");
Rel(ctrlUsuario, servUser, "usa");
Rel(ctrlLogin, servUser, "usa");
Rel(ctrlLogin, servLogin, "usa");

Rel(servLogin, goauth, "usa");
Rel(servEvent, bdados, "usa");
Rel(servNotifications, bdados, "usa");
Rel(servUser, bdados, "usa");


@enduml
