@startuml
' Split into 4 pages
page 2x2
skinparam pageMargin 10
skinparam pageExternalColor gray
skinparam pageBorderColor black


package BancoDeDados <<Database>> {
  
}

package API.Sistema <<Rectangle>> {

  namespace Evento #DDDDDD {
    class getEventsAll
    class getEventsByCourse
    class getEventsByDate
    class getEventByUser
    class postEvent
    class updateEvent
    class deleteEvent
    class createEventJsonKeys
    class timeLineEvents

  }
  
  namespace Notificacao {
    class getNotificationsByUserEmail
    class getNotificationsByCategory
    class updateNotification
    class deleteNotification
    
  }

  namespace Cursos {
    class getAllCourses
    class currentCourses
  }

  namespace Usuario {
    class getUser
    class saveUser
    class deleteUser
  }
}

Evento <|-- Cursos
Evento <|-- Notificacao

Usuario <|-- Evento
Usuario <|-- Cursos
Usuario <|-- Notificacao

BancoDeDados <|-- API.Sistema


@enduml